import type {
  Category,
  CategoryGroup,
  ChatMessage,
  Dispute,
  Job,
  Notification,
  Professional,
  Review,
  SearchTicket,
  User,
  AdminConfig,
} from "./types";

// DEMO seed data — not a source of truth. Replace with Supabase queries.

export const currentClient: User = {
  id: "u1",
  name: "Antía Bouzas",
  avatar: "AB",
  role: "client",
  location: "Vigo",
  email: "antia.bouzas@gmail.com",
  phone: "+34 666 000 000",
  memberSince: "feb 2023",
  rating: 4.9,
  reviews: 12,
  jobsPublished: 7,
  strikes: 0,
  verified: true,
};

export const currentPro: Professional = {
  id: "p1",
  name: "Manuel García Vázquez",
  avatar: "MG",
  specialty: "Electricista",
  specialties: ["Electricidad", "Domótica"],
  location: "Vigo",
  rating: 4.8,
  reviews: 23,
  verified: true,
  status: "approved",
  badge: "Top Profesional",
  jobs: 41,
  since: "feb 2023",
  responseTime: "< 1h",
  bio: "Electricista industrial con más de 12 años de experiencia en Galicia. Instalaciones residenciales, pequeñas empresas y pequeña domótica.",
  phone: "+34 600 111 222",
  email: "manuel.garcia@arranxos.gal",
  zone: "Vigo y área metropolitana",
  radiusKm: 25,
  reliability: 96,
  strikes: 0,
  completedOnTime: 98,
  avgPrice: "80–250€",
};

export const professionals: Professional[] = [
  {
    id: "p1",
    name: "Manuel García Vázquez",
    avatar: "MG",
    specialty: "Electricista",
    location: "Vigo",
    rating: 4.8,
    reviews: 23,
    verified: true,
    status: "approved",
    badge: "Top Profesional",
    jobs: 41,
    since: "feb 2023",
    responseTime: "< 1h",
    distance: "1.2 km",
    bio: "Electricista con 12 años de experiencia. Residencial e industrial.",
    reliability: 96,
    strikes: 0,
    completedOnTime: 98,
    lat: 42.237,
    lng: -8.72,
  },
  {
    id: "p2",
    name: "Carmen López Fernández",
    avatar: "CL",
    specialty: "Fontanera",
    location: "Santiago de Compostela",
    rating: 4.6,
    reviews: 17,
    verified: true,
    status: "approved",
    jobs: 28,
    since: "mar 2023",
    responseTime: "< 2h",
    distance: "3.5 km",
    bio: "Fontanera certificada. Averías, instalaciones y reformas de baño.",
    reliability: 92,
    strikes: 1,
    completedOnTime: 94,
    lat: 42.878,
    lng: -8.544,
  },
  {
    id: "p3",
    name: "Xosé Rodríguez Souto",
    avatar: "XR",
    specialty: "Carpintero",
    location: "A Coruña",
    rating: 4.9,
    reviews: 41,
    verified: true,
    status: "approved",
    badge: "Top Profesional",
    jobs: 67,
    since: "ene 2022",
    responseTime: "< 30 min",
    distance: "0.8 km",
    bio: "Carpintero artesanal. Tarimas, muebles a medida, restauración.",
    reliability: 98,
    strikes: 0,
    completedOnTime: 99,
    lat: 43.365,
    lng: -8.41,
  },
  {
    id: "p4",
    name: "Rosa Martínez Iglesias",
    avatar: "RM",
    specialty: "Pintora",
    location: "Pontevedra",
    rating: 0,
    reviews: 0,
    verified: false,
    status: "pending",
    jobs: 0,
    since: "abr 2024",
    responseTime: "—",
    distance: "2.1 km",
    strikes: 0,
    lat: 42.43,
    lng: -8.644,
  },
  {
    id: "p5",
    name: "Brais Nogueira Castro",
    avatar: "BN",
    specialty: "Albañil",
    location: "Ourense",
    rating: 0,
    reviews: 0,
    verified: false,
    status: "pending",
    jobs: 0,
    since: "may 2024",
    responseTime: "—",
    distance: "5.2 km",
    strikes: 0,
    lat: 42.336,
    lng: -7.864,
  },
  {
    id: "p6",
    name: "Iria Loureiro Paz",
    avatar: "IL",
    specialty: "Limpiadora",
    location: "Vigo",
    rating: 4.4,
    reviews: 9,
    verified: false,
    status: "approved",
    jobs: 14,
    since: "sep 2023",
    responseTime: "< 3h",
    distance: "1.8 km",
    reliability: 88,
    strikes: 0,
    completedOnTime: 90,
    lat: 42.24,
    lng: -8.712,
  },
  {
    id: "p7",
    name: "Suso Méndez Rivas",
    avatar: "SM",
    specialty: "Jardinero",
    location: "A Coruña",
    rating: 4.7,
    reviews: 18,
    verified: true,
    status: "approved",
    jobs: 26,
    since: "jun 2023",
    responseTime: "< 1h",
    distance: "4.1 km",
    bio: "Mantenimiento de jardines y podas de altura.",
    reliability: 93,
    strikes: 0,
    completedOnTime: 96,
    lat: 43.371,
    lng: -8.396,
  },
  {
    id: "p8",
    name: "Noa Ferreiro Vilas",
    avatar: "NF",
    specialty: "Diseñadora web",
    location: "Santiago de Compostela",
    rating: 4.9,
    reviews: 12,
    verified: true,
    status: "approved",
    badge: "Top Profesional",
    jobs: 15,
    since: "oct 2023",
    responseTime: "< 2h",
    distance: "2.4 km",
    bio: "Diseño web y tiendas online. Trabajo con comercios de Santiago y A Coruña.",
    reliability: 97,
    strikes: 0,
    completedOnTime: 100,
    lat: 42.881,
    lng: -8.546,
  },
  {
    id: "p9",
    name: "Roi Caamaño Lema",
    avatar: "RC",
    specialty: "Tractorista",
    location: "Lugo",
    rating: 4.5,
    reviews: 22,
    verified: true,
    status: "approved",
    jobs: 34,
    since: "mar 2023",
    responseTime: "< 3h",
    distance: "12.3 km",
    bio: "Labrado, fresado y transporte agrícola en A Terra Chá.",
    reliability: 90,
    strikes: 1,
    completedOnTime: 92,
    lat: 43.012,
    lng: -7.557,
  },
  {
    id: "p10",
    name: "Lucía Seoane Pardo",
    avatar: "LS",
    specialty: "Veterinaria",
    location: "Lugo",
    rating: 4.8,
    reviews: 31,
    verified: true,
    status: "approved",
    jobs: 48,
    since: "ene 2023",
    responseTime: "< 1h",
    distance: "8.7 km",
    bio: "Veterinaria a domicilio. Animales de granja y mascotas.",
    reliability: 98,
    strikes: 0,
    completedOnTime: 100,
    lat: 43.009,
    lng: -7.558,
  },
  {
    id: "p11",
    name: "Xoán Fraga Piñeiro",
    avatar: "XF",
    specialty: "Motoserrista",
    location: "Ourense",
    rating: 4.6,
    reviews: 14,
    verified: true,
    status: "approved",
    jobs: 20,
    since: "may 2023",
    responseTime: "< 4h",
    distance: "6.9 km",
    reliability: 89,
    strikes: 0,
    completedOnTime: 93,
    lat: 42.336,
    lng: -7.865,
  },
  {
    id: "p12",
    name: "Sabela Domínguez Varela",
    avatar: "SD",
    specialty: "Chef a domicilio",
    location: "Pontevedra",
    rating: 5.0,
    reviews: 8,
    verified: true,
    status: "approved",
    badge: "Top Profesional",
    jobs: 10,
    since: "ago 2023",
    responseTime: "< 2h",
    distance: "3.2 km",
    bio: "Cocina gallega moderna para eventos en casa.",
    reliability: 99,
    strikes: 0,
    completedOnTime: 100,
    lat: 42.433,
    lng: -8.648,
  },
  {
    id: "p13",
    name: "Pablo Estévez Vilariño",
    avatar: "PE",
    specialty: "Mecánico",
    location: "Vigo",
    rating: 4.3,
    reviews: 27,
    verified: true,
    status: "approved",
    jobs: 39,
    since: "feb 2023",
    responseTime: "< 2h",
    distance: "2.7 km",
    reliability: 86,
    strikes: 2,
    completedOnTime: 88,
    lat: 42.238,
    lng: -8.725,
  },
  {
    id: "p14",
    name: "Tania Rivas Cortizo",
    avatar: "TR",
    specialty: "Guía de rutas",
    location: "Santiago de Compostela",
    rating: 4.9,
    reviews: 19,
    verified: true,
    status: "approved",
    jobs: 24,
    since: "abr 2023",
    responseTime: "< 1h",
    distance: "5.5 km",
    bio: "Rutas por el Camino y por las Rías Baixas.",
    reliability: 96,
    strikes: 0,
    completedOnTime: 98,
    lat: 42.882,
    lng: -8.548,
  },
  {
    id: "p15",
    name: "Adrián Pérez Lois",
    avatar: "AP",
    specialty: "Cerrajero",
    location: "A Coruña",
    rating: 4.7,
    reviews: 16,
    verified: true,
    status: "approved",
    jobs: 22,
    since: "jul 2023",
    responseTime: "< 30 min",
    distance: "1.4 km",
    reliability: 94,
    strikes: 0,
    completedOnTime: 96,
    lat: 43.369,
    lng: -8.4,
  },
  {
    id: "p16",
    name: "Martiño Castro Bouza",
    avatar: "MC",
    specialty: "Albañil",
    location: "Vigo",
    rating: 3.2,
    reviews: 11,
    verified: false,
    status: "blocked",
    jobs: 13,
    since: "oct 2022",
    responseTime: "—",
    distance: "2.9 km",
    reliability: 52,
    strikes: 3,
    completedOnTime: 70,
    lat: 42.241,
    lng: -8.718,
  },
  {
    id: "p17",
    name: "Estrela Fernández Queiro",
    avatar: "EF",
    specialty: "Podadora en altura",
    location: "Pontevedra",
    rating: 4.8,
    reviews: 9,
    verified: false,
    status: "pending",
    jobs: 0,
    since: "abr 2024",
    responseTime: "—",
    distance: "4.8 km",
    strikes: 0,
    lat: 42.433,
    lng: -8.645,
  },
  {
    id: "p18",
    name: "Rubén Barros Otero",
    avatar: "RB",
    specialty: "Climatización",
    location: "Vigo",
    rating: 4.5,
    reviews: 21,
    verified: true,
    status: "approved",
    jobs: 30,
    since: "mar 2023",
    responseTime: "< 2h",
    distance: "1.9 km",
    reliability: 91,
    strikes: 0,
    completedOnTime: 94,
    lat: 42.235,
    lng: -8.723,
  },
  {
    id: "p19",
    name: "Anxo Viqueira Pose",
    avatar: "AV",
    specialty: "Drones",
    location: "A Coruña",
    rating: 4.8,
    reviews: 7,
    verified: true,
    status: "approved",
    jobs: 9,
    since: "nov 2023",
    responseTime: "< 3h",
    distance: "3.3 km",
    bio: "Vídeo y fotografía aérea. Inspección de cubiertas.",
    reliability: 95,
    strikes: 0,
    completedOnTime: 100,
    lat: 43.364,
    lng: -8.408,
  },
  {
    id: "p20",
    name: "Mateo Cundíns Rego",
    avatar: "MR",
    specialty: "Cristalero",
    location: "Ourense",
    rating: 4.2,
    reviews: 6,
    verified: false,
    status: "pending",
    jobs: 0,
    since: "may 2024",
    responseTime: "—",
    distance: "7.4 km",
    strikes: 0,
    lat: 42.336,
    lng: -7.863,
  },
];

// ── Jobs ─────────────────────────────────────────────────────────────────────
// Mix of statuses across 9 states; multiple concellos; varied price ranges.
export const jobs: Job[] = [
  {
    id: "j1",
    title: "Reparar enchufe y cuadro eléctrico",
    categoryId: "elec",
    category: "Electricidad",
    service: "Reparación eléctrica",
    location: "Coia, Vigo",
    locationApprox: "Zona sur de Vigo (aprox.)",
    lat: 42.215,
    lng: -8.744,
    status: "published",
    priceMin: 80,
    priceMax: 200,
    requests: 3,
    invitations: 1,
    posted: "hace 2 h",
    postedAt: "2026-04-20T07:30:00Z",
    clientId: "u1",
    clientName: "Antía B.",
    clientAvatar: "AB",
    clientRating: 4.9,
    description:
      "Tengo un enchufe que chisporrotea en el salón y el diferencial salta con frecuencia. Necesito revisar el cuadro eléctrico y reparar al menos dos enchufes. Piso de 70 m² en 3ª planta con ascensor.",
    hasPhotos: true,
  },
  {
    id: "j2",
    title: "Instalar tarima flotante en salón",
    categoryId: "manit",
    category: "Carpintería",
    service: "Tarima y suelos",
    location: "Ensanche, A Coruña",
    locationApprox: "Zona centro de A Coruña (aprox.)",
    lat: 43.366,
    lng: -8.411,
    status: "in_progress",
    priceMin: 300,
    priceMax: 700,
    finalPrice: 520,
    requests: 5,
    posted: "hace 1 d",
    postedAt: "2026-04-19T09:00:00Z",
    clientId: "u2",
    clientName: "Brais N.",
    clientAvatar: "BN",
    clientRating: 4.7,
    description:
      "Salón de 25 m² con tarima de pino vieja a reemplazar. Hay que levantar la tarima existente e instalar una nueva flotante de roble.",
    assignedProId: "p3",
    commissionPct: 9,
  },
  {
    id: "j3",
    title: "Reforma integral de baño",
    categoryId: "refo",
    category: "Reformas",
    service: "Reforma de baño",
    location: "Monte da Condesa, Santiago",
    locationApprox: "Zona oeste de Santiago (aprox.)",
    lat: 42.874,
    lng: -8.56,
    status: "escrow_funded",
    priceMin: 2000,
    priceMax: 4500,
    finalPrice: 3200,
    requests: 2,
    posted: "hace 3 d",
    postedAt: "2026-04-17T12:00:00Z",
    clientId: "u3",
    clientName: "Iria L.",
    clientAvatar: "IL",
    clientRating: 4.8,
    description:
      "Baño de 6 m² completo. Cambio de sanitarios, azulejo, fontanería e instalación eléctrica.",
    assignedProId: "p2",
    commissionPct: 9,
  },
  {
    id: "j4",
    title: "Pintar piso de 80 m²",
    categoryId: "pint",
    category: "Pintura",
    service: "Pintura interior",
    location: "A Ferrería, Pontevedra",
    locationApprox: "Centro de Pontevedra (aprox.)",
    lat: 42.432,
    lng: -8.644,
    status: "completed",
    priceMin: 400,
    priceMax: 800,
    finalPrice: 650,
    requests: 4,
    posted: "hace 12 d",
    postedAt: "2026-04-08T10:00:00Z",
    clientId: "u4",
    clientName: "Suso M.",
    clientAvatar: "SM",
    clientRating: 5.0,
    description:
      "Piso completo de 80 m². Pintura blanca en paredes, techos en color suave.",
    commissionPct: 9,
  },
  {
    id: "j5",
    title: "Arreglar gotera en cubierta",
    categoryId: "tejado",
    category: "Reformas",
    service: "Impermeabilización",
    location: "A Guarda, Pontevedra",
    locationApprox: "Sur de Pontevedra (aprox.)",
    lat: 41.903,
    lng: -8.873,
    status: "published",
    priceMin: 150,
    priceMax: 400,
    requests: 1,
    posted: "hace 30 min",
    postedAt: "2026-04-20T09:00:00Z",
    clientId: "u5",
    clientName: "Noa F.",
    clientAvatar: "NF",
    clientRating: 4.6,
    description:
      "Gotera en la cubierta plana de la terraza. Aparece agua en el techo del dormitorio cuando llueve.",
  },
  {
    id: "j6",
    title: "Instalar aire acondicionado split",
    categoryId: "clima",
    category: "Climatización",
    service: "Instalación de climatización",
    location: "Navia, Vigo",
    locationApprox: "Norte de Vigo (aprox.)",
    lat: 42.232,
    lng: -8.77,
    status: "agreement_pending",
    priceMin: 200,
    priceMax: 450,
    requests: 3,
    posted: "hace 4 h",
    postedAt: "2026-04-20T05:30:00Z",
    clientId: "u6",
    clientName: "Roi C.",
    clientAvatar: "RC",
    clientRating: 4.5,
    description:
      "Instalación de split 1×1 de 3000 frigorías. Aparato ya comprado, necesito solo la instalación.",
  },
  {
    id: "j7",
    title: "Poda de carballos en finca",
    categoryId: "podaltura",
    category: "Rural",
    service: "Poda de árboles",
    location: "Sarria, Lugo",
    locationApprox: "Comarca de Sarria (aprox.)",
    lat: 42.78,
    lng: -7.414,
    status: "published",
    priceMin: 350,
    priceMax: 800,
    requests: 2,
    posted: "hace 6 h",
    postedAt: "2026-04-20T03:30:00Z",
    clientId: "u7",
    clientName: "Xacobe P.",
    clientAvatar: "XP",
    clientRating: 4.8,
    description:
      "Poda de 12 carballos en finca de 1.500 m². Trabajos en altura, retirada de ramas.",
  },
  {
    id: "j8",
    title: "Desbroce de finca 4.000 m²",
    categoryId: "desbro",
    category: "Rural",
    service: "Desbroce mecanizado",
    location: "Muros, A Coruña",
    locationApprox: "Costa da Morte (aprox.)",
    lat: 42.78,
    lng: -9.058,
    status: "published",
    priceMin: 200,
    priceMax: 500,
    requests: 4,
    posted: "hace 2 d",
    postedAt: "2026-04-18T08:00:00Z",
    clientId: "u8",
    clientName: "Lois G.",
    clientAvatar: "LG",
    clientRating: 4.4,
    description: "Finca con maleza alta. Acceso para tractor desbrozador.",
  },
  {
    id: "j9",
    title: "Diseño web para taller mecánico",
    categoryId: "disweb",
    category: "Digital",
    service: "Creación de web",
    location: "Santiago de Compostela",
    locationApprox: "Santiago (aprox.)",
    lat: 42.88,
    lng: -8.545,
    status: "agreed",
    priceMin: 500,
    priceMax: 1500,
    finalPrice: 980,
    requests: 3,
    posted: "hace 5 d",
    postedAt: "2026-04-15T11:00:00Z",
    clientId: "u9",
    clientName: "Marcos T.",
    clientAvatar: "MT",
    clientRating: 4.9,
    description:
      "Web corporativa + reserva de cita online para taller mecánico en el casco histórico.",
    assignedProId: "p8",
    commissionPct: 9,
  },
  {
    id: "j10",
    title: "Reparar lavadora Bosch",
    categoryId: "electro",
    category: "Hogar",
    service: "Reparación lavadora",
    location: "O Calvario, Vigo",
    locationApprox: "Sur de Vigo (aprox.)",
    lat: 42.22,
    lng: -8.73,
    status: "published",
    priceMin: 50,
    priceMax: 180,
    requests: 2,
    posted: "hace 1 h",
    postedAt: "2026-04-20T08:30:00Z",
    clientId: "u10",
    clientName: "Paula R.",
    clientAvatar: "PR",
    clientRating: 4.7,
    description:
      "Lavadora no centrifuga y hace un ruido raro al desaguar. Modelo de 2019.",
  },
  {
    id: "j11",
    title: "Cambio de cerradura urgente",
    categoryId: "cerra",
    category: "Hogar",
    service: "Cambio de cerradura",
    location: "Os Mallos, A Coruña",
    locationApprox: "Zona sur de A Coruña (aprox.)",
    lat: 43.358,
    lng: -8.416,
    status: "completed",
    priceMin: 80,
    priceMax: 180,
    finalPrice: 120,
    requests: 3,
    posted: "hace 7 d",
    postedAt: "2026-04-13T14:00:00Z",
    clientId: "u11",
    clientName: "Helena M.",
    clientAvatar: "HM",
    clientRating: 4.8,
    description: "Necesito cambiar la cerradura de seguridad de la entrada.",
    commissionPct: 9,
  },
  {
    id: "j12",
    title: "Instalación riego por goteo en huerta",
    categoryId: "riego",
    category: "Rural",
    service: "Instalación de riego",
    location: "Betanzos, A Coruña",
    locationApprox: "Zona de Betanzos (aprox.)",
    lat: 43.28,
    lng: -8.213,
    status: "published",
    priceMin: 250,
    priceMax: 600,
    requests: 1,
    posted: "hace 3 h",
    postedAt: "2026-04-20T06:30:00Z",
    clientId: "u12",
    clientName: "Emilio D.",
    clientAvatar: "ED",
    clientRating: 4.5,
    description: "Huerta de 600 m². Quiero riego por goteo programable.",
  },
  {
    id: "j13",
    title: "Limpieza post-obra piso 90 m²",
    categoryId: "limp",
    category: "Hogar",
    service: "Limpieza post-obra",
    location: "Cangas, Pontevedra",
    locationApprox: "Morrazo (aprox.)",
    lat: 42.264,
    lng: -8.782,
    status: "dispute",
    priceMin: 180,
    priceMax: 350,
    finalPrice: 280,
    requests: 2,
    posted: "hace 14 d",
    postedAt: "2026-04-06T09:00:00Z",
    clientId: "u13",
    clientName: "Uxía C.",
    clientAvatar: "UC",
    clientRating: 4.3,
    description: "Piso reformado, quedan restos de yeso y pintura.",
    disputeOpenedAt: "2026-04-19T10:00:00Z",
    disputeReason: "Trabajo incompleto",
    commissionPct: 9,
  },
  {
    id: "j14",
    title: "Veterinario a domicilio para ternera",
    categoryId: "vet",
    category: "Ganadería",
    service: "Visita a domicilio",
    location: "Castro de Rei, Lugo",
    locationApprox: "A Terra Chá (aprox.)",
    lat: 43.205,
    lng: -7.451,
    status: "agreed",
    priceMin: 70,
    priceMax: 180,
    finalPrice: 120,
    requests: 1,
    posted: "hace 8 h",
    postedAt: "2026-04-20T01:30:00Z",
    clientId: "u14",
    clientName: "Manuel G.",
    clientAvatar: "MG",
    clientRating: 4.7,
    description: "Ternera con fiebre, necesita revisión urgente.",
    assignedProId: "p10",
    commissionPct: 9,
  },
  {
    id: "j15",
    title: "Vendimia manual 2 hectáreas",
    categoryId: "vendim",
    category: "Campañas agrícolas",
    service: "Vendimia manual",
    location: "Leiro, Ourense",
    locationApprox: "Ribeiro (aprox.)",
    lat: 42.365,
    lng: -8.119,
    status: "published",
    priceMin: 800,
    priceMax: 2000,
    requests: 5,
    posted: "hace 2 d",
    postedAt: "2026-04-18T06:00:00Z",
    clientId: "u15",
    clientName: "Bodega Pazo de Sar",
    clientAvatar: "BP",
    clientRating: 4.9,
    description:
      "Vendimia de viñedos en ladera. Necesitamos cuadrilla experimentada. Manutención incluida.",
  },
  {
    id: "j16",
    title: "Pintar valla y fachada exterior",
    categoryId: "pint",
    category: "Pintura",
    service: "Pintura exterior",
    location: "Ribadeo, Lugo",
    locationApprox: "Mariña Oriental (aprox.)",
    lat: 43.535,
    lng: -7.041,
    status: "published",
    priceMin: 450,
    priceMax: 900,
    requests: 2,
    posted: "hace 5 h",
    postedAt: "2026-04-20T04:30:00Z",
    clientId: "u16",
    clientName: "Xulia C.",
    clientAvatar: "XC",
    clientRating: 4.6,
    description: "Fachada de 80 m² y valla perimetral. Color actual blanco roto.",
  },
  {
    id: "j17",
    title: "DJ para boda — 120 invitados",
    categoryId: "sonido",
    category: "Eventos",
    service: "DJ",
    location: "Cambados, Pontevedra",
    locationApprox: "O Salnés (aprox.)",
    lat: 42.513,
    lng: -8.811,
    status: "agreed",
    priceMin: 600,
    priceMax: 1400,
    finalPrice: 900,
    requests: 4,
    posted: "hace 6 d",
    postedAt: "2026-04-14T17:00:00Z",
    clientId: "u17",
    clientName: "Noelia R.",
    clientAvatar: "NR",
    clientRating: 4.8,
    description:
      "Boda en pazo el sábado. Ceremonia + cocktail + cena + barra libre. Sonido e iluminación incluidos.",
    commissionPct: 9,
  },
  {
    id: "j18",
    title: "Montar mueble IKEA PAX",
    categoryId: "manit",
    category: "Hogar",
    service: "Montaje de muebles",
    location: "Teis, Vigo",
    locationApprox: "Este de Vigo (aprox.)",
    lat: 42.25,
    lng: -8.71,
    status: "published",
    priceMin: 40,
    priceMax: 120,
    requests: 6,
    posted: "hace 45 min",
    postedAt: "2026-04-20T08:15:00Z",
    clientId: "u18",
    clientName: "Álex F.",
    clientAvatar: "AF",
    clientRating: 4.7,
    description:
      "Armario PAX 2 m con puertas correderas. Tengo todas las piezas.",
  },
  {
    id: "j19",
    title: "Limpieza fosa séptica comunidad",
    categoryId: "fosasep",
    category: "Rural",
    service: "Limpieza fosa séptica",
    location: "Boiro, A Coruña",
    locationApprox: "Barbanza (aprox.)",
    lat: 42.64,
    lng: -8.89,
    status: "completed_pending_confirmation",
    priceMin: 180,
    priceMax: 400,
    finalPrice: 280,
    requests: 1,
    posted: "hace 10 d",
    postedAt: "2026-04-10T08:00:00Z",
    clientId: "u19",
    clientName: "Comunidade O Forno",
    clientAvatar: "CF",
    clientRating: 4.4,
    description: "Limpieza anual de fosa séptica comunitaria para 8 vecinos.",
    completionDeadline: "2026-04-25T12:00:00Z",
    commissionPct: 9,
  },
  {
    id: "j20",
    title: "Recoger tractor averiado",
    categoryId: "mecan",
    category: "Motor",
    service: "Mecánica rápida",
    location: "Melide, A Coruña",
    locationApprox: "A Terra de Melide (aprox.)",
    lat: 42.917,
    lng: -7.997,
    status: "published",
    priceMin: 150,
    priceMax: 350,
    requests: 1,
    posted: "hace 1 h",
    postedAt: "2026-04-20T08:00:00Z",
    clientId: "u20",
    clientName: "Xan P.",
    clientAvatar: "XP",
    clientRating: 4.6,
    description:
      "Tractor parado en una corredoira. Necesito remolque y revisión inicial.",
  },
  {
    id: "j21",
    title: "Cortar 10 m³ de leña",
    categoryId: "motosierra",
    category: "Rural",
    service: "Corte de leña",
    location: "Forcarei, Pontevedra",
    locationApprox: "Terra de Montes (aprox.)",
    lat: 42.614,
    lng: -8.359,
    status: "published",
    priceMin: 200,
    priceMax: 500,
    requests: 3,
    posted: "hace 4 h",
    postedAt: "2026-04-20T05:30:00Z",
    clientId: "u21",
    clientName: "María C.",
    clientAvatar: "MC",
    clientRating: 4.5,
    description: "Troncos de eucalipto y pino ya talados. Cortar y apilar.",
  },
  {
    id: "j22",
    title: "Instalar domótica — luces y persianas",
    categoryId: "domo",
    category: "Digital",
    service: "Instalación domótica",
    location: "Oleiros, A Coruña",
    locationApprox: "Golfo Ártabro (aprox.)",
    lat: 43.33,
    lng: -8.32,
    status: "escrow_funded",
    priceMin: 800,
    priceMax: 2000,
    finalPrice: 1450,
    requests: 2,
    posted: "hace 4 d",
    postedAt: "2026-04-16T10:00:00Z",
    clientId: "u22",
    clientName: "Daniel V.",
    clientAvatar: "DV",
    clientRating: 4.8,
    description:
      "Chalet unifamiliar. Luces controladas por voz, persianas automatizadas.",
    assignedProId: "p1",
    commissionPct: 9,
  },
  {
    id: "j23",
    title: "Grabar vídeo aéreo para promoción inmobiliaria",
    categoryId: "drones",
    category: "Digital",
    service: "Vídeo aéreo",
    location: "Sanxenxo, Pontevedra",
    locationApprox: "O Salnés (aprox.)",
    lat: 42.403,
    lng: -8.806,
    status: "published",
    priceMin: 250,
    priceMax: 600,
    requests: 2,
    posted: "hace 20 h",
    postedAt: "2026-04-19T13:30:00Z",
    clientId: "u23",
    clientName: "Pazo Inmobiliaria",
    clientAvatar: "PI",
    clientRating: 4.9,
    description:
      "Vídeo aéreo + fotos de pazo de 800 m² para publicación web.",
  },
  {
    id: "j24",
    title: "Chef a domicilio — cena 10 pax",
    categoryId: "gastro",
    category: "Eventos",
    service: "Chef a domicilio",
    location: "Poio, Pontevedra",
    locationApprox: "Ría de Pontevedra (aprox.)",
    lat: 42.443,
    lng: -8.681,
    status: "published",
    priceMin: 400,
    priceMax: 900,
    requests: 3,
    posted: "hace 8 h",
    postedAt: "2026-04-20T01:30:00Z",
    clientId: "u24",
    clientName: "Pablo X.",
    clientAvatar: "PX",
    clientRating: 4.7,
    description:
      "Cena de cumpleaños para 10. Cocina de mercado gallega. Maridaje opcional.",
  },
  {
    id: "j25",
    title: "Reparar calentador de gas",
    categoryId: "cald",
    category: "Hogar",
    service: "Reparación caldera",
    location: "Ferrol",
    locationApprox: "Ferrolterra (aprox.)",
    lat: 43.484,
    lng: -8.235,
    status: "published",
    priceMin: 80,
    priceMax: 250,
    requests: 4,
    posted: "hace 2 h",
    postedAt: "2026-04-20T07:30:00Z",
    clientId: "u25",
    clientName: "Teresa F.",
    clientAvatar: "TF",
    clientRating: 4.6,
    description:
      "Calentador de gas no calienta. Ya se revisó la llave, falla el quemador.",
  },
  {
    id: "j26",
    title: "Transporte de 4 vacas",
    categoryId: "transgan",
    category: "Ganadería",
    service: "Transporte ganado",
    location: "Palas de Rei, Lugo",
    locationApprox: "A Ulloa (aprox.)",
    lat: 42.874,
    lng: -7.868,
    status: "cancelled",
    priceMin: 150,
    priceMax: 400,
    requests: 2,
    posted: "hace 6 d",
    postedAt: "2026-04-14T09:00:00Z",
    clientId: "u26",
    clientName: "Ganadería Souto",
    clientAvatar: "GS",
    clientRating: 4.5,
    description: "Traslado de 4 vacas a una feria en Silleda.",
  },
  {
    id: "j27",
    title: "Ruta senderista guiada 8 personas",
    categoryId: "guia",
    category: "Turismo",
    service: "Rutas de senderismo",
    location: "Ribeira Sacra, Lugo",
    locationApprox: "Ribeira Sacra (aprox.)",
    lat: 42.388,
    lng: -7.539,
    status: "published",
    priceMin: 150,
    priceMax: 400,
    requests: 3,
    posted: "hace 1 d",
    postedAt: "2026-04-19T10:00:00Z",
    clientId: "u27",
    clientName: "Rosa X.",
    clientAvatar: "RX",
    clientRating: 4.8,
    description: "Ruta de 4 h por cañones del Sil. Grupo de amigos.",
  },
  {
    id: "j28",
    title: "Cámara de vigilancia para comercio",
    categoryId: "camaras",
    category: "Digital",
    service: "Cámaras de vigilancia",
    location: "Pontevedra",
    locationApprox: "Pontevedra (aprox.)",
    lat: 42.432,
    lng: -8.644,
    status: "agreement_pending",
    priceMin: 400,
    priceMax: 900,
    requests: 2,
    posted: "hace 18 h",
    postedAt: "2026-04-19T15:30:00Z",
    clientId: "u28",
    clientName: "Libraría Meiga",
    clientAvatar: "LM",
    clientRating: 4.7,
    description: "Instalación de 4 cámaras en librería. Acceso remoto.",
  },
  {
    id: "j29",
    title: "Reforma pequeña cocina — cambio de encimera",
    categoryId: "refo",
    category: "Reformas",
    service: "Pequeñas reformas",
    location: "Marín, Pontevedra",
    locationApprox: "Ría de Pontevedra (aprox.)",
    lat: 42.393,
    lng: -8.702,
    status: "in_progress",
    priceMin: 400,
    priceMax: 900,
    finalPrice: 680,
    requests: 3,
    posted: "hace 9 d",
    postedAt: "2026-04-11T11:00:00Z",
    clientId: "u29",
    clientName: "Clara R.",
    clientAvatar: "CR",
    clientRating: 4.6,
    description: "Cambiar encimera de formica por granito. Fregadero nuevo.",
    commissionPct: 9,
  },
  {
    id: "j30",
    title: "Limpieza de pozo para agua potable",
    categoryId: "lpozo",
    category: "Rural",
    service: "Limpieza de pozos",
    location: "Vilagarcía de Arousa",
    locationApprox: "O Salnés (aprox.)",
    lat: 42.595,
    lng: -8.763,
    status: "published",
    priceMin: 200,
    priceMax: 500,
    requests: 0,
    posted: "hace 40 min",
    postedAt: "2026-04-20T08:20:00Z",
    clientId: "u30",
    clientName: "Martín L.",
    clientAvatar: "ML",
    clientRating: 4.7,
    description: "Pozo de 8 m. Agua con sabor raro, necesito limpieza y análisis.",
  },
  {
    id: "j31",
    title: "Mantenimiento de jardín mensual",
    categoryId: "jard",
    category: "Hogar",
    service: "Mantenimiento de jardín",
    location: "Oleiros, A Coruña",
    locationApprox: "Golfo Ártabro (aprox.)",
    lat: 43.331,
    lng: -8.324,
    status: "completed",
    priceMin: 60,
    priceMax: 120,
    finalPrice: 85,
    requests: 2,
    posted: "hace 20 d",
    postedAt: "2026-03-31T09:00:00Z",
    clientId: "u31",
    clientName: "Lucas B.",
    clientAvatar: "LB",
    clientRating: 4.9,
    description: "Jardín de 200 m². Poda, riego, abono.",
    commissionPct: 9,
  },
  {
    id: "j32",
    title: "Control de ocupación en vivienda vacía",
    categoryId: "okup",
    category: "Hogar",
    service: "Vigilancia",
    location: "A Coruña",
    locationApprox: "A Coruña (aprox.)",
    lat: 43.371,
    lng: -8.395,
    status: "published",
    priceMin: 200,
    priceMax: 500,
    requests: 1,
    posted: "hace 3 d",
    postedAt: "2026-04-17T10:00:00Z",
    clientId: "u32",
    clientName: "Inversiones Miño",
    clientAvatar: "IM",
    clientRating: 4.5,
    description:
      "Piso vacío desde hace meses. Necesito inspección + cambio de accesos.",
  },
  {
    id: "j33",
    title: "Restaurar mesa de castaño antigua",
    categoryId: "rest",
    category: "Hogar",
    service: "Restauración de muebles",
    location: "Monforte de Lemos, Lugo",
    locationApprox: "Terra de Lemos (aprox.)",
    lat: 42.521,
    lng: -7.507,
    status: "completed_pending_confirmation",
    priceMin: 180,
    priceMax: 400,
    finalPrice: 260,
    requests: 2,
    posted: "hace 12 d",
    postedAt: "2026-04-08T14:00:00Z",
    clientId: "u33",
    clientName: "Familia Lamas",
    clientAvatar: "FL",
    clientRating: 4.8,
    description: "Mesa de castaño del siglo XIX. Barnizado y refuerzo de patas.",
    completionDeadline: "2026-04-24T18:00:00Z",
    commissionPct: 9,
  },
  {
    id: "j34",
    title: "Clases de kayak en ría",
    categoryId: "multiadv",
    category: "Turismo",
    service: "Kayak",
    location: "Baiona, Pontevedra",
    locationApprox: "Val Miñor (aprox.)",
    lat: 42.123,
    lng: -8.848,
    status: "published",
    priceMin: 150,
    priceMax: 400,
    requests: 1,
    posted: "hace 7 h",
    postedAt: "2026-04-20T02:30:00Z",
    clientId: "u34",
    clientName: "Pedro R.",
    clientAvatar: "PR",
    clientRating: 4.7,
    description: "Iniciación para grupo de 4. Material incluido.",
  },
  {
    id: "j35",
    title: "Esquila de rebaño de 50 ovejas",
    categoryId: "esquila",
    category: "Ganadería",
    service: "Esquilador",
    location: "A Fonsagrada, Lugo",
    locationApprox: "Os Ancares (aprox.)",
    lat: 43.122,
    lng: -7.071,
    status: "published",
    priceMin: 300,
    priceMax: 700,
    requests: 2,
    posted: "hace 1 d",
    postedAt: "2026-04-19T09:00:00Z",
    clientId: "u35",
    clientName: "Curro M.",
    clientAvatar: "CM",
    clientRating: 4.5,
    description: "Esquila de temporada para rebaño de 50 ovejas.",
  },
];

// ── Categories (expanded from original) ──────────────────────────────────────
export const categoryGroups: CategoryGroup[] = [
  {
    group: "Hogar",
    icon: "🏠",
    color: "#EEF4FB",
    categories: [
      { id: "limp", name: "Limpieza", icon: "🧹", services: ["Limpieza doméstica", "Limpieza post-obra", "Cristales", "Comunidades"] },
      { id: "planch", name: "Plancha", icon: "👔", services: ["Servicio de plancha", "Plancha a domicilio"] },
      { id: "manit", name: "Manitas", icon: "🔨", services: ["Pequeñas reparaciones", "Montaje de muebles", "Instalaciones", "Bricolaje"] },
      { id: "mudan", name: "Mudanzas y portes", icon: "📦", services: ["Mudanza local", "Mudanza interurbana", "Portes", "Embalaje", "Guardamuebles"] },
      { id: "font", name: "Fontanería", icon: "🔧", services: ["Reparación de averías", "Instalación sanitaria", "Calefacción", "Calentadores"] },
      { id: "pint", name: "Pintura", icon: "🎨", services: ["Pintura interior", "Pintura exterior", "Barnices y lacados", "Decoración"] },
      { id: "elec", name: "Electricista", icon: "⚡", services: ["Instalación eléctrica", "Reparación eléctrica", "Cuadros y fusibles", "Puntos de luz"] },
      { id: "electro", name: "Electrodomésticos", icon: "🫙", services: ["Reparación lavadora", "Reparación frigorífico", "Reparación lavavajillas", "Instalación"] },
      { id: "refo", name: "Reformas", icon: "🏗", services: ["Reforma de cocina", "Reforma de baño", "Reforma integral", "Pequeñas reformas"] },
      { id: "jard", name: "Jardinería", icon: "🌿", services: ["Mantenimiento jardín", "Poda y corte", "Diseño de jardín", "Riego automático"] },
      { id: "cerra", name: "Cerrajero", icon: "🔑", services: ["Apertura de urgencia", "Cambio de cerradura", "Copia de llaves", "Seguridad"] },
      { id: "clima", name: "Climatización", icon: "🌡", services: ["Instalación aire acondicionado", "Mantenimiento", "Calefacción", "Bomba de calor"] },
      { id: "casav", name: "Cuidado casas vacías", icon: "🏡", services: ["Vigilancia periódica", "Mantenimiento", "Aireado", "Gestión de incidencias"] },
      { id: "finca", name: "Revisión de fincas", icon: "🌾", services: ["Inspección de finca", "Mantenimiento", "Fotografía aérea", "Informe de estado"] },
      { id: "okup", name: "Control de ocupación", icon: "🛡", services: ["Vigilancia", "Inspección", "Gestión de accesos", "Asesoría legal"] },
      { id: "rest", name: "Restaurador", icon: "🪑", services: ["Restauración de muebles", "Tapizado", "Barnizado", "Piezas antiguas"] },
      { id: "tejado", name: "Reparación de tejados", icon: "🏠", services: ["Reparación de goteras", "Impermeabilización", "Sustitución de tejas", "Canalones"] },
      { id: "cald", name: "Calderas y chimeneas", icon: "🔥", services: ["Limpieza de caldera", "Deshollinado", "Revisión de chimenea", "Mantenimiento"] },
    ],
  },
  {
    group: "Rural / Agrario",
    icon: "🚜",
    color: "#FEF5E7",
    categories: [
      { id: "tract", name: "Tractorista", icon: "🚜", services: ["Labrado", "Fresado", "Transporte", "Siembra mecanizada"] },
      { id: "excav", name: "Excavadora", icon: "⛏", services: ["Excavación", "Movimiento de tierras", "Nivelación", "Drenajes"] },
      { id: "podaltura", name: "Podador en altura", icon: "🌳", services: ["Poda de árboles", "Tala controlada", "Limpieza de copas", "Trabajos en altura"] },
      { id: "motosierra", name: "Motoserrista", icon: "🪚", services: ["Tala de árboles", "Corte de leña", "Desbroce", "Limpieza forestal"] },
      { id: "lparcela", name: "Limpieza de parcelas", icon: "🌱", services: ["Desbroce manual", "Retirada de residuos", "Limpieza post-cosecha"] },
      { id: "desbro", name: "Desbroce", icon: "🌿", services: ["Desbroce mecanizado", "Desbroce manual", "Cunetas", "Taludes"] },
      { id: "lpozo", name: "Limpieza de pozos", icon: "💧", services: ["Vaciado de pozos", "Limpieza", "Inspección", "Reparación"] },
      { id: "riego", name: "Riego", icon: "💦", services: ["Instalación de riego", "Riego por goteo", "Mantenimiento", "Aspersores"] },
      { id: "remolque", name: "Remolque", icon: "🚛", services: ["Transporte agrícola", "Remolque de maquinaria", "Portes rurales"] },
      { id: "inver", name: "Invernaderos", icon: "🌡", services: ["Construcción", "Mantenimiento", "Instalación climatización", "Reparación"] },
      { id: "fosasep", name: "Limpieza fosas sépticas", icon: "🔩", services: ["Vaciado de fosa", "Limpieza", "Inspección", "Reparación"] },
    ],
  },
  {
    group: "Ganadería",
    icon: "🐄",
    color: "#FCE9CC",
    categories: [
      { id: "vet", name: "Veterinario domicilio", icon: "🩺", services: ["Visita a domicilio", "Vacunación", "Urgencias", "Seguimiento"] },
      { id: "transgan", name: "Transporte de ganado", icon: "🐄", services: ["Transporte vacuno", "Transporte ovino", "Transporte porcino"] },
      { id: "esquila", name: "Esquilador", icon: "🐑", services: ["Esquila de ovino", "Esquila de caprino", "Servicio a domicilio"] },
      { id: "cercado", name: "Instalación cercados", icon: "🔗", services: ["Valla ganadera", "Cercado eléctrico", "Reparación", "Instalación de puertas"] },
      { id: "lcuadra", name: "Limpieza cuadras", icon: "🧽", services: ["Limpieza y desinfección", "Retirada de residuos", "Cama de animales"] },
    ],
  },
  {
    group: "Campañas Agrícolas",
    icon: "🍇",
    color: "#F7D5D5",
    categories: [
      { id: "vendim", name: "Vendimia", icon: "🍇", services: ["Vendimia manual", "Vendimia mecanizada", "Transporte de uva"] },
      { id: "aceitun", name: "Aceituna", icon: "🫒", services: ["Recogida de aceituna", "Vareo", "Transporte"] },
      { id: "fruta", name: "Fruta", icon: "🍎", services: ["Recogida de fruta", "Clasificación", "Embalaje"] },
      { id: "siembre", name: "Siembra", icon: "🌱", services: ["Siembra manual", "Siembra mecanizada", "Preparación de terreno"] },
      { id: "herbic", name: "Aplicación herbicida", icon: "🌿", services: ["Aplicación fitosanitarios", "Tratamiento herbicida", "Fungicida"] },
      { id: "recolec", name: "Recolección patata / maíz", icon: "🌽", services: ["Recogida de patata", "Recogida de maíz", "Transporte"] },
    ],
  },
  {
    group: "Digital / Tecnológica",
    icon: "💻",
    color: "#D6E4F3",
    categories: [
      { id: "domo", name: "Domótica", icon: "📡", services: ["Instalación domótica", "Automatización del hogar", "Asistentes de voz", "Control remoto"] },
      { id: "inform", name: "Informática", icon: "💻", services: ["Reparación de ordenadores", "Instalación software", "Virus y malware", "Redes"] },
      { id: "disweb", name: "Diseño web", icon: "🌐", services: ["Creación de web", "Landing page", "Tienda online", "Mantenimiento web"] },
      { id: "rrss", name: "Gestión redes sociales", icon: "📱", services: ["Instagram", "Facebook", "TikTok", "Estrategia de contenidos"] },
      { id: "camaras", name: "Cámaras de vigilancia", icon: "📷", services: ["Instalación", "Configuración remota", "Mantenimiento", "Sistemas de alarma"] },
      { id: "drones", name: "Drones", icon: "🚁", services: ["Vídeo aéreo", "Fotografía aérea", "Vigilancia", "Topografía"] },
    ],
  },
  {
    group: "Motor / Movilidad",
    icon: "🚗",
    color: "#FFE1E2",
    categories: [
      { id: "mecan", name: "Mecánica rápida", icon: "🔧", services: ["Cambio de aceite", "Cambio de ruedas", "Revisión rápida", "Frenos"] },
      { id: "lavauto", name: "Limpieza / Aspiración", icon: "🚿", services: ["Lavado exterior", "Lavado interior", "Encerado", "Desinfección"] },
      { id: "itv", name: "ITV (recogida / entrega)", icon: "🚗", services: ["Recogida y entrega para ITV", "Acompañamiento", "Gestión de documentación"] },
      { id: "condpriv", name: "Conductor privado", icon: "🎩", services: ["Traslados", "Aeropuerto", "Eventos", "Conductor designado"] },
    ],
  },
  {
    group: "Eventos / Ocio",
    icon: "🎉",
    color: "#E2DAF4",
    categories: [
      { id: "gastro", name: "Gastronomía", icon: "🍽", services: ["Cortador de jamón", "Camareros", "Chef a domicilio", "Bartender"] },
      { id: "animac", name: "Animación", icon: "🎪", services: ["Magos", "Atracciones", "Animadores infantiles", "Shows"] },
      { id: "sonido", name: "Sonido", icon: "🎵", services: ["DJ", "Duos musicales", "Grupos", "Sonorización de eventos"] },
    ],
  },
  {
    group: "Turismo",
    icon: "🗺",
    color: "#D6EDE7",
    categories: [
      { id: "guia", name: "Guía de rutas", icon: "🥾", services: ["Rutas de senderismo", "Rutas en bici", "Rutas históricas", "Camino de Santiago"] },
      { id: "multiadv", name: "Multiaventura", icon: "🧗", services: ["Kayak", "Escalada", "Rappel", "Tirolina", "Rafting"] },
    ],
  },
];

export const categories: Category[] = categoryGroups.flatMap((g) =>
  g.categories.map((c) => ({
    id: c.id,
    name: c.name,
    icon: c.icon,
    services: c.services,
    group: g.group,
    color: g.color,
  })),
);

// ── Chat (demo conversation for j1) ──────────────────────────────────────────
export const chatMessages: ChatMessage[] = [
  { id: "m1", jobId: "j1", from: "pro",    text: "Buenos días Antía. Revisé su solicitud; puedo pasarme el miércoles a valorar el trabajo.", time: "10:23", timestamp: "2026-04-20T08:23:00Z", type: "text" },
  { id: "m2", jobId: "j1", from: "client", text: "Perfecto Manuel, el miércoles por la tarde me va bien. ¿Sobre las 17 h?", time: "10:31", timestamp: "2026-04-20T08:31:00Z", type: "text" },
  { id: "m3", jobId: "j1", from: "pro",    text: "De acuerdo. Le mando propuesta antes de ir para que lo vaya valorando.", time: "10:32", timestamp: "2026-04-20T08:32:00Z", type: "text" },
  { id: "m4", jobId: "j1", from: "system", text: "Manuel envió una propuesta", time: "10:45", timestamp: "2026-04-20T08:45:00Z", type: "proposal", proposalAmount: 160 },
  { id: "m5", jobId: "j1", from: "client", text: "Me parece un poco alto. ¿Podría ajustarlo a 130 €?", time: "11:02", timestamp: "2026-04-20T09:02:00Z", type: "text" },
  { id: "m6", jobId: "j1", from: "pro",    text: "Puedo dejarlo en 145 € con todo incluido, materiales y mano de obra con garantía.", time: "11:15", timestamp: "2026-04-20T09:15:00Z", type: "text" },
  { id: "m7", jobId: "j1", from: "system", text: "Acuerdo aceptado · Pago protegido activado", time: "11:20", timestamp: "2026-04-20T09:20:00Z", type: "agreement", proposalAmount: 145 },
  { id: "m8", jobId: "j1", from: "client", text: "Perfecto, hasta el miércoles entonces.", time: "11:21", timestamp: "2026-04-20T09:21:00Z", type: "text" },
];

// ── Reviews ──────────────────────────────────────────────────────────────────
export const reviews: Review[] = [
  { id: "r1", author: "Iria L.", avatar: "IL", rating: 5, text: "Manuel llegó puntual, hizo el trabajo en poco tiempo y dejó todo limpio. Muy profesional.", date: "mar 2026", targetId: "p1", targetType: "professional", jobId: "j4" },
  { id: "r2", author: "Roi C.",  avatar: "RC", rating: 5, text: "Resolvió el problema del cuadro eléctrico en menos de una hora. Precio justo.", date: "feb 2026", targetId: "p1", targetType: "professional" },
  { id: "r3", author: "Noa F.",  avatar: "NF", rating: 4, text: "Buen trabajo. Tardó un poco más de lo previsto pero el resultado fue perfecto.", date: "ene 2026", targetId: "p1", targetType: "professional" },
  { id: "r4", author: "Helena M.", avatar: "HM", rating: 5, text: "Adrián vino en 30 minutos y cambió la cerradura perfectamente.", date: "abr 2026", targetId: "p15", targetType: "professional", jobId: "j11" },
  { id: "r5", author: "Clara R.", avatar: "CR", rating: 4, text: "Trabajo bien hecho pero algo tarde.", date: "abr 2026", targetId: "p2", targetType: "professional" },
  { id: "r6", author: "Manuel G.", avatar: "MG", rating: 5, text: "Antía fue muy clara con lo que necesitaba. Cliente excelente.", date: "mar 2026", targetId: "u1", targetType: "client" },
];

// ── Notifications ────────────────────────────────────────────────────────────
export const notifications: Notification[] = [
  { id: "n1", text: "Manuel García solicita participar en tu trabajo", sub: "Reparar enchufe y cuadro eléctrico", time: "hace 5 min", unread: true, type: "request", jobId: "j1" },
  { id: "n2", text: "Xosé Rodríguez acepta tu propuesta de 520 €", sub: "Instalar tarima flotante en salón", time: "hace 2 h", unread: true, type: "agreement", jobId: "j2" },
  { id: "n3", text: "Tu trabajo fue valorado con 5 estrellas", sub: "Pintar piso de 80 m²", time: "hace 1 d", unread: false, type: "review", jobId: "j4" },
  { id: "n4", text: "Pago liberado al profesional", sub: "Cambio de cerradura urgente · 120 €", time: "hace 2 d", unread: false, type: "payment", jobId: "j11" },
  { id: "n5", text: "Se ha abierto una disputa", sub: "Limpieza post-obra piso 90 m²", time: "hace 1 d", unread: true, type: "dispute", jobId: "j13" },
];

// ── Disputes ─────────────────────────────────────────────────────────────────
export const disputes: Dispute[] = [
  {
    id: "d1",
    jobId: "j13",
    openedBy: "client",
    reason: "Trabajo incompleto",
    description:
      "Al llegar aún había restos de yeso en el baño y la cocina. El profesional se fue sin terminar.",
    status: "open",
    openedAt: "2026-04-19T10:00:00Z",
    evidence: ["foto1.jpg", "foto2.jpg"],
  },
];

// ── Search tickets (cliente pide pros en zona sin oferta) ────────────────────
export const searchTickets: SearchTicket[] = [
  {
    id: "t1",
    clientId: "u30",
    clientName: "Martín L.",
    service: "Limpieza de pozos",
    zone: "Vilagarcía de Arousa",
    radiusKm: 15,
    createdAt: "2026-04-20T08:30:00Z",
    status: "open",
  },
  {
    id: "t2",
    clientId: "u14",
    clientName: "Manuel G.",
    service: "Esquilador",
    zone: "A Fonsagrada",
    radiusKm: 40,
    createdAt: "2026-04-18T07:00:00Z",
    status: "matched",
  },
];

// ── Admin config (editable) ──────────────────────────────────────────────────
export const defaultAdminConfig: AdminConfig = {
  commissionPct: 9,
  autoReleaseDays: 5,
  invitationLimitPerJob: 10,
  strikeAutoBlockThreshold: 3,
  antiLeakEnabled: true,
  antiLeakRules: {
    phones: true,
    emails: true,
    urls: true,
    whatsapp: true,
  },
};

// ── Lookup helpers ───────────────────────────────────────────────────────────
export function jobById(id: string) {
  return jobs.find((j) => j.id === id);
}
export function proById(id: string) {
  return professionals.find((p) => p.id === id);
}
export function categoryById(id: string) {
  return categories.find((c) => c.id === id);
}
export function reviewsForPro(id: string) {
  return reviews.filter((r) => r.targetId === id && r.targetType === "professional");
}
export function reviewsForClient(id: string) {
  return reviews.filter((r) => r.targetId === id && r.targetType === "client");
}
