-- ARRANXOS v3 - Supabase Phase 1
-- File: 01_seed.sql
-- Purpose: Optional seed data for controlled local/staging verification.
-- Execution order: 2 of 5
--
-- IMPORTANT:
-- - Do NOT execute SQL that has not been reviewed.
-- - SQL in this repository must be non-destructive by default.
-- - Do NOT use destructive DROP statements unless they are in a dedicated file
--   and explicitly approved in review.
--
-- NOTE:
-- - This file is an initial placeholder for structure only.
-- - Do not add real production seeds in this phase.
