-- ARRANXOS v3 - Supabase Phase 1
-- File: 02_rls_policies.sql
-- Purpose: Row Level Security enablement and policies.
-- Execution order: 3 of 5
--
-- IMPORTANT:
-- - Do NOT execute SQL that has not been reviewed.
-- - SQL in this repository must be non-destructive by default.
-- - Do NOT use destructive DROP statements unless they are in a dedicated file
--   and explicitly approved in review.
--
-- NOTE:
-- - This file is an initial placeholder for structure only.
-- - Add policies only after schema and access model review.
