-- ARRANXOS v3 - Supabase Phase 1
-- File: 04_indexes.sql
-- Purpose: Performance indexes added after schema and access patterns settle.
-- Execution order: 5 of 5
--
-- IMPORTANT:
-- - Do NOT execute SQL that has not been reviewed.
-- - SQL in this repository must be non-destructive by default.
-- - Do NOT use destructive DROP statements unless they are in a dedicated file
--   and explicitly approved in review.
--
-- NOTE:
-- - This file is an initial placeholder for structure only.
-- - Add indexes incrementally based on measured query patterns.
